- tools/transform.js
Hi there,
as discussed with @ralfhandl, this pull request adds an ```--verbose``` option to ```transform.js``. When using this option, additional progress information while transformation is in progress is added.
Feedback is appreciated.
Regards,
Florian
> Added a verbose option to transform.js for additional progress information

- lib/csdl2openapi.js
- package.json
- test/csdl2openapi.test.js
Suppress qualifier in action/function paths if they are defined in a default namespace
> Default Namespaces and action/function paths

- lib/csdl2openapi.js
- package.json
- Check for `@odata.type` and `@type` in authorization annotations
> Check for @odata.type in authorization annotations

- examples/TripPin.openapi3.json
- examples/annotations.openapi3.json
- examples/authorization.openapi3.json
- examples/containment.openapi3.json
- examples/csdl-16.1.openapi3.json
- examples/descriptions.openapi3.json
- examples/example.openapi3.json
- examples/miscellaneous.openapi3.json
- examples/odata-rw-v3.openapi3.json
- lib/csdl2openapi.js
- test/csdl2openapi.test.js
- tools/V4-CSDL-to-OpenAPI.xsl
- tools/tests/Northwind-key-as-segment.openapi3.json
- tools/tests/Northwind-key-as-segment.swagger.json
- tools/tests/TripPin.openapi3.json
- tools/tests/TripPin.swagger.json
- tools/tests/annotations.openapi3.json
- tools/tests/annotations.swagger.json
- tools/tests/authorization.openapi3.json
- tools/tests/authorization.swagger.json
- tools/tests/containment.openapi3.json
- tools/tests/containment.swagger.json
- tools/tests/csdl-16.1.openapi3.json
- tools/tests/csdl-16.1.swagger.json
- tools/tests/descriptions.openapi3.json
- tools/tests/descriptions.swagger.json
- tools/tests/odata-rw-v2.openapi3.json
- tools/tests/odata-rw-v2.swagger.json
- tools/tests/odata-rw-v3.openapi3.json
- tools/tests/odata-rw-v3.swagger.json
> feat: adds count property to collection result

- README.md
Changed contact info from named staff to tc-admin@ email address.
> Changed contact info to tc-admin@

- examples/People.openapi3.json
- examples/People.xml
- examples/Products.openapi3.json
- examples/Products.xml
> More key-as-segment

- .github/workflows/nodejs.yml
Node.js 14.15.0 is now the current LTS version
> CI with Node.js.14.x 

- tools/V4-CSDL-to-OpenAPI.xsl
- tools/package.json
- tools/tests/annotations.openapi3.json
- tools/tests/annotations.swagger.json
- tools/tests/annotations.xml
And deal correctly with schema aliases
Resolves https://github.com/oasis-tcs/odata-openapi/pull/107
> Test case for mandatory properties

- tools/V4-CSDL-to-OpenAPI.xsl
- tools/package.json
- Pull out string constants
- use `xsl:key` for element lookup
- use `xsl:for-each` for looping over child elements
> XSLT refactored

- CHANGELOG.md
- examples/Northwind-V3.openapi3.json
- examples/Northwind-key-as-segment.openapi3.json
- examples/Northwind.openapi3.json
- examples/People.openapi3.json
- examples/Products.openapi3.json
- examples/TripPin.openapi3.json
- examples/annotations.openapi3.json
- examples/example.openapi3.json
- examples/odata-rw-v3.openapi3.json
- lib/README.md
- lib/cli.js
- lib/csdl2openapi.js
- lib/transform.js
- package-lock.json
- package.json
- test/csdl2openapi.test.js
- tools/README.md
- tools/lib/validate.js
- tools/package.json
Fixes #207
- command-line parameter for OpenAPI version
- OAS 3.1.0
- test coverage
- bug fixes for Double and Float
- README
- Changelog
- bump version
> OpenAPI Version 3.1.0

- examples/odata-rw-v2.openapi3.json
- examples/odata-rw-v2.xml
- package-lock.json
- package.json
> OData V2: Documentation for FunctionImport and Parameter

- CHANGELOG.md
- examples/TitleAndDescription.openapi3.json
- lib/README.md
- lib/cli.js
- lib/csdl2openapi.js
- package-lock.json
- package.json
- test/csdl2openapi.test.js
- Added support for title and description 
- fixed smaller CLI issues
- Doc update how to use locally
> Title and description support

- .vscode/extensions.json
- examples/annotations.openapi3.json
- lib/csdl2openapi.js
- package-lock.json
- package.json
- test/csdl2openapi-examples.test.js
- test/csdl2openapi.test.js
- test/examples.test.js
- test/utilities.js
- bump package version
- bump dependencies
- remove outdated VS Code extension recommendations
- split testcases into two files plus utilities
> Fix: decimal minimum and maximum only if precision and scale are present and numeric

- .eslintrc.json
- CHANGELOG.md
- lib/csdl2openapi.js
- lib/diagram.js
- lib/edm.js
- package-lock.json
- package.json
- test/csdl2openapi.test.js
- test/examples.test.js
- extract CSDL access into EDM class
- keep only pure OpenAPI production in csdl2openapi.js
> Refactor code

- tools/V4-CSDL-to-OpenAPI.xsl
- tools/package-lock.json
- tools/package.json
- tools/tests/annotations.openapi3.json
- tools/tests/annotations.swagger.json
- tools/tests/annotations.xml
Also accept `Capabilities.KeyAsSegmentSupported` with external targeting
> XSLT: KeyAsSegmentSupported with external targeting

- CHANGELOG.md
- lib/csdl2openapi.js
- lib/edm.js
- package-lock.json
- package.json
- test/csdl2openapi.test.js
- test/funnyInput.test.js
Fixes #248 
- first scan all schemas, then process annotations in a second pass
> Fix for issue 248

- CHANGELOG.md
- lib/edm.js
- package-lock.json
- package.json
- test/funnyInput.test.js
> Fix: inheritance across schemas

- CHANGELOG.md
- lib/diagram.js
- package-lock.json
- package.json
- test/annotations.test.js
- test/csdl2openapi.test.js
- Complex types and type definitions were sometimes colored as entity types
- Action/function color was unnecessarily repeated in relationships to input parameter types
> Fix: color in diagrams

- CHANGELOG.md
- examples/Products.openapi3.json
- examples/containment.openapi3.json
- examples/descriptions.openapi3.json
- examples/example.openapi3.json
- examples/odata-rw-v3.openapi3.json
- lib/csdl2openapi.js
- package-lock.json
- package.json
- test/csdl2openapi.test.js
Returns a `value` wrapper with the primitive inside
> Fix: action or function returns primitive value

- tools/transform.js
> XSLT: write xsl:message output to stdout instead of stderr

- package.json
Prevent test coverage from dropping below 100%
> Require full test coverage
